# Generated by Django 5.1.6 on 2025-07-30 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('variedad_cafe', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_quintales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cosecha', models.DateField()),
                ('estado', models.CharField(choices=[('preparacion', 'En Preparación'), ('proceso', 'En Proceso'), ('analisis', 'En Análisis'), ('finalizado', 'Finalizado')], default='preparacion', max_length=20)),
                ('propietarios', models.TextField(help_text='JSON con información de propietarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesos.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Muestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_muestra', models.CharField(max_length=50)),
                ('peso_gramos', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_analisis', 'En Análisis'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True)),
                ('humedad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('defectos', models.IntegerField(blank=True, null=True)),
                ('puntaje_taza', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_resultado', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procesos.lote')),
            ],
        ),
    ]
